name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          clean: true
      -
        name: 'Use Node.js 16.x'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: 'Install Package'
        run: 'npm install --global stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'stargazed --username "witoszekdev" --token ${GITHUB_TOKEN} --repo "awesome-stars" --message "stargazed update by GitHub Actions Workflow" --sort'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          message: "Update stargazed repos"
          push: true
          pull: '--rebase --autostash'
